lee-ji-hoon/community

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/account/AccountController.java
- src/main/java/com/community/account/AccountService.java
- src/main/java/com/community/profile/Profile.java
- src/main/java/com/community/profile/ProfileController.java
- src/main/resources/templates/account/profile.html
- src/main/resources/templates/fragments.html
- src/main/resources/templates/settings/profile-settings.html
> 프로필 뷰 및 수정페이지

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/board/Board.java
- src/main/java/com/community/board/BoardController.java
- src/main/java/com/community/board/BoardForm.java
- src/main/java/com/community/board/BoardService.java
- src/main/resources/templates/board/board-list.html
- src/main/resources/templates/board/board-write.html
- src/main/resources/templates/board/detail.html
- src/main/resources/templates/board/edit.html
- src/main/resources/templates/fragments.html
> summernote 추가

- src/main/java/com/community/board/controller/BoardController.java
- src/main/java/com/community/forum/Forum.java
- src/main/java/com/community/forum/ForumController.java
- src/main/java/com/community/forum/ForumReply.java
- src/main/resources/static/package-lock.json
- src/main/resources/static/package.json
- src/main/resources/templates/board/blog-read.html
- src/main/resources/templates/board/blogs.html
- src/main/resources/templates/forum/forum-detail.html
- src/main/resources/templates/forum/forum-write.html
- src/main/resources/templates/forum/forums.html
> 게시글 수정 및 삭제 알람 추가 포럼 write 추가

- src/main/java/com/community/MainController.java
- src/main/java/com/community/board/controller/BoardController.java
- src/main/java/com/community/board/controller/ReplyController.java
- src/main/java/com/community/board/service/BoardService.java
- src/main/java/com/community/council/CouncilController.java
- src/main/java/com/community/council/CouncilRepository.java
- src/main/java/com/community/council/CouncilService.java
- src/main/resources/application-dev.properties
- src/main/resources/application.properties
- src/main/resources/static/package-lock.json
- src/main/resources/static/package.json
- src/main/resources/templates/board/blog-read.html
- src/main/resources/templates/board/blogs.html
- src/main/resources/templates/council/council-posts.html
- src/main/resources/templates/council/detail.html
- src/main/resources/templates/index.html
- src/main/resources/templates/theme-fragments.html
`/council/council-posts 40번 ~ 179번줄 확인 부탁`
기존에 있던 a태그(모달 창을 여는 버튼)는 수정할 필요 없고 
`<div id="create-post-modal" uk-modal>...</div>`
이 폼을 가져가서 안에 내용을 맞게 수정하면 됌 모르면 해드림
> 커뮤니티, 학생회 종합 수정

- .gitignore
- src/main/java/com/community/MainController.java
- src/main/java/com/community/report/ReportController.java
- src/main/resources/templates/board/blog-read.html
- src/main/resources/templates/council/detail.html
- src/main/resources/templates/index.html
- src/main/resources/templates/report-form.html
> index 및 report 로직 수정

- src/main/java/com/community/study/StudyController.java
- src/main/resources/templates/study/study-meetings.html
> 댓글 작성 수정 삭제 성공

- src/main/java/com/community/web/controller/ChatController.java
- src/main/resources/application-dev.properties
- src/main/resources/application.properties
- src/main/resources/templates/chat/chat-detail.html
- src/main/resources/templates/market/market-detail.html
쪽지를 조회하기 위해서는 우선 DB에서만 볼 수 있음
Chat 엔티티 중에서 Market은 추후에 마켓에서 쪽지를 보내면 쪽지 내용에 해당 상품을 띄워줄 예정임
-> 당근마켓에서 해당 상품에 대한 채팅을 보내면 상품 정보가 상단에 뜨는 것과 같은 느낌
> 장터 쪽지 보내기 구현 완료

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/domain/account/Account.java
- src/main/java/com/community/domain/study/Study.java
- src/main/java/com/community/service/AccountService.java
- src/main/java/com/community/service/StudyService.java
- src/main/java/com/community/web/controller/AccountController.java
- src/main/java/com/community/web/dto/ProfileForm.java
- src/main/resources/templates/account/profile.html
- src/main/resources/templates/settings/password.html
- src/main/resources/templates/study/settings/description.html
- src/main/resources/templates/study/study-form.html
- src/main/resources/templates/theme-fragments.html
> profile-view

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/domain/account/Account.java
- src/main/java/com/community/domain/chat/ChatRepository.java
- src/main/java/com/community/domain/chat/Room.java
- src/main/java/com/community/service/ChatService.java
- src/main/java/com/community/web/controller/BaseController.java
- src/main/java/com/community/web/controller/ChatController.java
- src/main/resources/application-dev.properties
- src/main/resources/templates/chat/chat-detail.html
- src/main/resources/templates/theme-fragments.html
-> 채팅방에서 사용하는 data-simplebar가 header에도 적용되어 있음을 확인
-> 알람 , 쪽지 드롭다운이 스크롤이 되도록 설계 되어있어서 스크롤을 제거함
-> TDI에서도 제거함
-> model 보낼 때 `g_name` 형식으로 !
-> 쪽지 알람에서 들어가면 알람은 사라지지 않음
-> 채팅방 목록에서 해당 채팅방을 클릭하면 header가 새로 load되면서 알람이 지워짐
> 전역 Controller 생성 및 쪽지 ReadChk 버그 수정

- .gitignore
- build.gradle
- src/main/java/com/community/domain/market/Market.java
- src/main/java/com/community/service/MarketService.java
- src/main/java/com/community/service/S3Service.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/dto/MarketForm.java
- src/main/resources/application-dev.properties
- src/main/resources/application.properties
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-list.html
- src/main/resources/templates/study/study-view.html
- src/main/resources/templates/theme-fragments.html
> 이메일 인증 로직 / AWS s3 / dev-properties ignore

- src/main/java/com/community/web/controller/MarketController.java
- src/main/resources/application.properties
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-form.html
- src/main/resources/templates/market/market-list.html
> market form 분리 및 로직 변경 / properties RDS 권한자 변경

- src/main/java/com/community/manager/ManagerController.java
- src/main/java/com/community/manager/ManagerService.java
- src/main/java/com/community/manager/ManagerSettlement.java
- src/main/resources/templates/manager-fragments.html
> Kajunyoung

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/domain/account/Account.java
- src/main/java/com/community/domain/market/Market.java
- src/main/java/com/community/domain/market/MarketItemStatus.java
- src/main/java/com/community/domain/market/MarketRepository.java
- src/main/java/com/community/domain/market/MarketRepositoryExtension.java
- src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
- src/main/java/com/community/service/MarketService.java
- src/main/java/com/community/service/ProfileService.java
- src/main/java/com/community/service/S3Service.java
- src/main/java/com/community/web/controller/AccountController.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/controller/ProfileController.java
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-form.html
- src/main/resources/templates/market/market-list.html
- src/main/resources/templates/theme-fragments.html
-> controller 단으로도 안넘어가는 것으로 보아 view에서 문제거나 security 문제로 보임 
-> [market delete update put 작동 -> put 에서 특정 이미지들 업로드 안됨 -> 이유 찾아야 함](https://github.com/lee-ji-hoon/community/pull/323/commits/24f8d1e6d676dba147dce3c0d6326031f664638c) **해결**
> market image delete 버그 해결 / s3 CloudFront로 접근 / market 페이징 작업 진행중

- src/main/java/com/community/domain/board/Board.java
- src/main/java/com/community/domain/board/BoardRepository.java
- src/main/java/com/community/domain/council/Council.java
- src/main/java/com/community/domain/council/CouncilRepository.java
- src/main/java/com/community/manager/ManagerController.java
- src/main/java/com/community/manager/ManagerService.java
- src/main/java/com/community/service/BoardService.java
- src/main/java/com/community/service/CouncilService.java
- src/main/java/com/community/web/controller/BoardController.java
- src/main/java/com/community/web/controller/CouncilController.java
- src/main/java/com/community/web/controller/ReplyController.java
- src/main/java/com/community/web/dto/BoardForm.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/boards.html
- src/main/resources/templates/council/councils.html
- src/main/resources/templates/manager-fragments.html
> Council 페이징 처리(공지만) / Board 수정 로직 변경(ajax 제거)

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/infra/config/SecurityConfig.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/controller/StudyController.java
- src/main/java/com/community/web/dto/MarketForm.java
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-form.html
- src/main/resources/templates/market/market-list.html
> csrf 토큰 설정 / 페이징 작업 중

- src/main/java/com/community/web/controller/CouncilController.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/council/councils.html
> Council 페이징 처리(notice)

- src/main/java/com/community/domain/market/Market.java
- src/main/java/com/community/domain/market/MarketRepository.java
- src/main/java/com/community/domain/market/MarketRepositoryExtension.java
- src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
- src/main/java/com/community/service/MarketService.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/controller/ProfileController.java
- src/main/java/com/community/web/controller/SearchController.java
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-list.html
- src/main/resources/templates/profile/view.html
- src/main/resources/templates/theme-fragments.html
> profile 작업 진행 중

- src/main/java/com/community/domain/board/BoardRepository.java
- src/main/java/com/community/web/controller/BoardController.java
- src/main/java/com/community/web/controller/ProfileController.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/boards.html
- src/main/resources/templates/profile/view.html
> Profile Board+Pagination 적용 / View 단 좋아요, 댓글 로직 변경

- src/main/java/com/community/domain/board/BoardRepository.java
- src/main/java/com/community/service/BoardService.java
- src/main/java/com/community/web/controller/BoardController.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/boards.html
**변경 전**
- pageView로만 정렬
**변경 후**
- pageView + likeList.size() + replyList.size() 전체를 더해서 정렬
> 실시간 인기글 로직 수정

- src/main/java/com/community/manager/ManagerController.java
- src/main/java/com/community/manager/ManagerService.java
- src/main/java/com/community/web/controller/MainController.java
- src/main/resources/templates/index.html
- src/main/resources/templates/manager-fragments.html
- src/main/resources/templates/manager/m_board.html
- src/main/resources/templates/manager/m_main.html
- src/main/resources/templates/manager/maps.html
- src/main/resources/templates/manager/settings.html
- src/main/resources/templates/manager/tables.html
> Top5 Boards 로직 변경 / Index 부분 제거 및 링크 수정 / Manager View 수정 및 로직 추가

- src/main/java/com/community/domain/board/Board.java
- src/main/java/com/community/domain/council/Council.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/bookmark/bookmarks.html
Bookmark가 들어간 Entity에 아래 내용 추가하셈 study, market에만 추가하면 될듯 ~.~
```java
@OneToMany(mappedBy = "board", cascade = CascadeType.ALL, orphanRemoval = true)
private List<Bookmark> bookmarkList = new ArrayList<>();
```
> Bookmark View 수정 / Entity별 BookmarkList 추가

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/domain/market/MarketRepository.java
- src/main/java/com/community/domain/market/MarketRepositoryExtension.java
- src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
- src/main/java/com/community/domain/study/StudyRepository.java
- src/main/java/com/community/infra/config/SecurityConfig.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/controller/StudyController.java
- src/main/resources/templates/bookmark/bookmarks.html
- src/main/resources/templates/market/market-form.html
- src/main/resources/templates/market/market-list.html
- src/main/resources/templates/market/market-search.html
- src/main/resources/templates/study/study-view.html
- src/main/resources/templates/theme-fragments.html
```java
<th:block th:if="${market.marketItemStatus.equals(market.marketItemStatus.SOLDOUT)}">
```
- `MarketController` - 81
- `market-list` - 61
- `market-search` - 결과view
> study 북마크 / market 검색 / graduation (졸작) 추가

- src/main/java/com/community/domain/council/Council.java
- src/main/java/com/community/domain/likes/LikeRepository.java
- src/main/java/com/community/domain/likes/Likes.java
- src/main/java/com/community/domain/market/Market.java
- src/main/java/com/community/domain/study/Study.java
- src/main/java/com/community/service/LikeService.java
- src/main/java/com/community/service/ReplyService.java
- src/main/java/com/community/web/controller/CouncilController.java
- src/main/java/com/community/web/controller/LikeApiController.java
- src/main/java/com/community/web/controller/ReplyController.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/bookmark/bookmarks.html
- src/main/resources/templates/council/council-detail.html
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/theme-fragments.html
```java
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "market.marketItemStatus.equals(market.marketItemStatus.SELLING)" (template: "bookmark/bookmarks" - line 46, col 51)
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "market.marketItemStatus.equals(market.marketItemStatus.SELLING)" (template: "bookmark/bookmarks" - line 46, col 51)
```
두 번째 사진에 자유, 정보, 질문 이런 식으로 들어갈 예정임
> Council Like 추가 / Board View 버그 수정 / Reply Ajax Fragments로 이동 / 북마크 페이지 수정 진행중

- src/main/java/com/community/infra/aws/S3.java
- src/main/java/com/community/infra/aws/S3Repository.java
- src/main/java/com/community/service/GraduationService.java
- src/main/java/com/community/web/controller/GraduationController.java
- src/main/resources/static/package-lock.json
- src/main/resources/static/package.json
- src/main/resources/templates/graduation/graduation-form.html
- src/main/resources/templates/graduation/graduation-list.html
- src/main/resources/templates/graduation/graduation-view.html
- src/main/resources/templates/theme-fragments.html
> 졸업작품 이미지 수정 / update / delete 

- src/main/java/com/community/TestDataInit.java
- src/main/java/com/community/domain/graduation/Graduation.java
- src/main/java/com/community/domain/graduation/GraduationRepository.java
- src/main/java/com/community/domain/graduation/GraduationRepositoryExtension.java
- src/main/java/com/community/domain/graduation/GraduationRepositoryExtensionImpl.java
- src/main/java/com/community/web/controller/GraduationController.java
- src/main/resources/templates/graduation/graduation-form.html
- src/main/resources/templates/graduation/graduation-list.html
- src/main/resources/templates/graduation/graduation-search.html
- src/main/resources/templates/graduation/graduation-view.html
- src/main/resources/templates/theme-fragments.html
> 졸작 페이징 추가 / 피드백 수정

- src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
- src/main/java/com/community/infra/aws/S3Controller.java
- src/main/java/com/community/infra/aws/S3Service.java
- src/main/java/com/community/service/GraduationService.java
- src/main/java/com/community/service/MarketService.java
- src/main/java/com/community/web/controller/GraduationController.java
- src/main/java/com/community/web/controller/MarketController.java
- src/main/java/com/community/web/controller/ProfileController.java
- src/main/resources/templates/graduation/graduation-view.html
- src/main/resources/templates/market/market-detail.html
- src/main/resources/templates/market/market-form.html
- src/main/resources/templates/market/market-list.html
- src/main/resources/templates/profile/view.html
- src/main/resources/templates/theme-fragments.html
```javascript
// 코드의 변동사항이 많음 이미지 삭제를 각각의 컨트롤러보단 하나의 컨트롤러에서 해결하는 방식으로 바꿈 
// 스크립트
function imageDeleteInit(id) {
$.ajax({
type: "GET",
contentType: "application/x-www-form-urlencoded; charset=utf-8",
url: "/s3/image/delete",
data: {"imageId": id},
success : function (){
$('.refreshForm').load(location.href+' .refreshForm');
$('.imageRefreshForm').load(location.href+' .imageRefreshForm');
},
})
}
```
```java
//  s3Service / s3Controller
@ResponseBody
@RequestMapping(value = "/s3/image/delete", method = RequestMethod.GET)
public ResponseEntity graduationDeleteImage(@RequestParam(value = "imageId", required = false) int imageId) {
log.info("s3 id 값 : {}", imageId);
Optional<S3> byId = s3Repository.findById(Long.valueOf(imageId));
S3 s3 = byId.get();
s3Service.deleteImage(s3);
return …
```
> 멀티이미지 각각의 delete 성공 / 마켓 및 프로필 버그 해결

- src/main/java/com/community/domain/council/Council.java
- src/main/java/com/community/service/CouncilService.java
- src/main/java/com/community/web/controller/CouncilController.java
- src/main/resources/templates/council/council-detail.html
- src/main/resources/templates/council/councils.html
> Council LocalDateTime 변경

- src/main/java/com/community/web/controller/InfoPageController.java
- src/main/resources/templates/info/info-about.html
- src/main/resources/templates/info/info-notice-detail.html
- src/main/resources/templates/info/info-notice.html
> Notice 페이지 수정

- src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
- src/main/java/com/community/web/controller/InfoPageController.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/boards.html
- src/main/resources/templates/council/council-detail.html
- src/main/resources/templates/info/info-notice-detail.html
- src/main/resources/templates/theme-fragments.html
```html
<th:block th:if="${board.getImageList().size() !=0}">
<div class="uk-container my-4" uk-slider>
<div class="uk-position-relative uk-visible-toggle uk-light">
<div class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m">
<div th:each="image : ${board.getImageList()}">
<a th:href="${image.getImagePath()}" data-fancybox="gallery">
</a>
</div>
</div>
<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>
</div>
</div>
<hr class="pb-2">
</th:block>
```
> 서비스 약관 제거 / Board top5 쿼리 로직 수정중(미완성) / Board 수정 안 되는 버그 수정

- build.gradle
- src/main/java/com/community/infra/config/SecurityConfig.java
- src/main/java/com/community/infra/config/SecurityUser.java
- src/main/java/com/community/service/AccountService.java
- src/main/java/com/community/service/CustomUserDetailsService.java
- src/main/java/com/community/service/ProfileService.java
- src/main/java/com/community/web/controller/AccountController.java
- src/main/resources/templates/board/boards.html
- src/main/resources/templates/fragments/head.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/side-bar.html
- src/main/resources/templates/layout/layout.html
`deprecated`된 `WebSecurityConfigurerAdapter`를 제거하고, `SecurityFilterChain`으로 변경
추후에 비회원도 열람은 가능하도록 변경하기 위해 로직 단순화
> Account 로직 변경

- build.gradle
- src/main/java/com/community/Community.java
- src/main/java/com/community/app/util/Ut.java
- src/main/java/com/community/domain/base/BaseEntity.java
- src/main/java/com/community/domain/board/Board.java
- src/main/java/com/community/domain/board/BoardRepository.java
- src/main/java/com/community/infra/alarm/LikeEventListener.java
- src/main/java/com/community/infra/alarm/ReplyEventListener.java
- src/main/java/com/community/infra/config/SecurityConfig.java
- src/main/java/com/community/service/BoardService.java
- src/main/java/com/community/service/BookmarkService.java
- src/main/java/com/community/service/LikeService.java
- src/main/java/com/community/service/ReplyService.java
- src/main/java/com/community/web/controller/AccountController.java
- src/main/java/com/community/web/controller/BoardController.java
- src/main/java/com/community/web/controller/LikeApiController.java
- src/main/java/com/community/web/controller/MainController.java
- src/main/java/com/community/web/controller/ReplyController.java
- src/main/java/com/community/web/controller/ReportController.java
- src/main/java/com/community/web/controller/SearchController.java
- src/main/java/com/community/web/controller/WebErrorController.java
- src/main/java/com/community/web/dto/LoginRequest.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/boards.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/index.html
- src/main/resources/templates/layout/layout.html
- src/main/resources/templates/login-form.html
- 비회원이 main, boards까지 조회 가능
- SecurityConfig 재구현
> Account 기능 개발

- src/main/java/com/community/service/BoardService.java
- src/main/java/com/community/web/controller/BoardController.java
- 게시글 삭제 후 리다이렉트 되는 주소 통일화
- 불필요한 로직 구성이라 판단
- 현재 로그인한 유저가 게시글의 작성자인지에 대한 방어 로직 개선
- Controller에 잔존하는 비즈니스 로직(작성자와 로그인 유저 확인) 모듈화
> 게시글 삭제 로직 수정
